contact_links:
  - name: Help & Support
    url: https://github.com/agence-adeliom/sylius-tailwindcss-theme/discussions/categories/q-a
    about: Please don't create issues for personal help requests. Instead, ask your question on the discussion forum.