# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.1/charts/other/app-template/values.schema.json
# --
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/common-3.0.3/charts/library/common/values.yaml
#        
controllers:
  main:
    type: deployment
    strategy: Recreate
    containers:
      main:
        image:
          # -- image repository
          repository: docker.io/adeliom/sylius-tailwindcss-theme
          # -- image tag
          # this example is not automatically updated, so be sure to use the latest image
          tag: "{{.Chart.AppVersion}}"
          # -- image pull policy
          pullPolicy: Always
        # -- environment variables.
        # @default -- See [values.yaml](./values.yaml)
        env: {}
        envFrom:
        - configMap: config

        probes:
          readiness:
            enabled: true
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                - sh
                - -c
                - "exit 1"
              failureThreshold: 1
              initialDelaySeconds: 120
              periodSeconds: 3600


# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      external-dns.alpha.kubernetes.io/hostname: &host sylius-tailwind.adeliom.io
    hosts:
    - host: *host
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: http
    tls:
    - secretName: sylius-tailwind-tls
      hosts:
      - *host

# -- Configure configMaps for the chart here.
configMaps:
  config:
    enabled: true
    data:
      APP_ENV: prod
      DATABASE_URL: mysql://sylius:changeme@{{ .Release.Name }}-mariadb:3306/sylius?serverVersion=10.11.7-MariaDB&charset=utf8mb4
      TRUSTED_PROXIES: 127.0.0.1,10.0.0.0/8,REMOTE_ADDR

# -- Enable and configure mariadb database subchart under this key.
#    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
# @default -- See [values.yaml](./values.yaml)
mariadb:
  enabled: false
  auth:
    database: sylius
    username: sylius
    password: changeme
    rootPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi
