name: Install & Test
'on':
    push:
        branches:
            - 0.x
        paths-ignore:
            - README.md
    pull_request:
        paths-ignore:
            - README.md
jobs:
    sylius:
        name: 'Sylius ${{ matrix.sylius }} Node ${{ matrix.node }}'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php:
                    - 8.2
                sylius:
                    - 1.12.0
                symfony:
                    - 6.4
                node:
                    - 20.x
        env:
            APP_ENV: test
            package-name: agence-adeliom/sylius-tailwindcss-theme
        steps:
            -
                name: 'Setup PHP'
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '${{ matrix.php }}'
                    ini-values: date.timezone=UTC
                    extensions: intl
                    tools: symfony
                    coverage: none
            -
                name: 'Setup Node'
                uses: actions/setup-node@v3
                with:
                    node-version: '${{ matrix.node }}'
            -
                uses: actions/checkout@v3
            -
                name: 'Composer - Get Cache Directory'
                id: composer-cache
                run: 'echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT'
            -
                name: 'Composer - Set cache'
                uses: actions/cache@v3
                id: cache-composer
                with:
                    path: '${{ steps.composer-cache.outputs.dir }}'
                    key: 'php-${{ matrix.php }}-sylius-${{ matrix.sylius }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles(''**/composer.json'') }}'
                    restore-keys: 'php-${{ matrix.php }}-sylius-${{ matrix.sylius }}-symfony-${{ matrix.symfony }}-composer-'
            -
                name: 'Composer - Create cache directory'
                run: 'mkdir -p /home/runner/.composer/cache'
                if: 'steps.cache-composer.outputs.cache-hit != ''true'''
            -
                name: 'Composer - Github Auth'
                run: 'composer config -g github-oauth.github.com ${{ github.token }}'
                
            -   name: Cache node modules
                id: cache-npm
                uses: actions/cache@v3
                env:
                    cache-name: cache-node-modules
                with:
                    # npm cache files are stored in `~/.npm` on Linux/macOS
                    path: ~/.npm
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-
                        ${{ runner.os }}-build-
                        ${{ runner.os }}-

            -   if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
                name: List the state of node modules
                continue-on-error: true
                run: npm list    
                
            -
                name: 'Install Sylius-Standard and Plugin'
                run: 'make install-ci -e SYLIUS_VERSION=${{ matrix.sylius }} SYMFONY_VERSION=${{ matrix.symfony }} PHP_VERSION=${{ matrix.php }}'
            -
                name: 'Output PHP version for Symfony CLI'
                working-directory: ./install/Application
                run: 'php -v | head -n 1 | awk ''{ print $2 }'' > .php-version'
            -
                name: 'Install certificates'
                working-directory: ./install/Application
                run: 'symfony server:ca:install'
            -
                name: 'Run webserver'
                working-directory: ./install/Application
                run: 'symfony server:start --port=8080 --dir=public --daemon'
            -
                name: 'Run PHPUnit'
                run: 'make phpunit-ci'
        services:
            mariadb:
                image: 'mariadb:10'
                ports:
                    - '3306:3306'
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: true
                options: '--health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3'
